version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        VARIANT: "11"
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
    command: sleep infinity
    env_file: .env
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2
